#!/usr/bin/env python3
"""Writes design/ART_CHECKLIST.md: every picture the game asks for.

    python3 tools/art_checklist.py

Reads data/art.json for where each kind of picture lives, and the data files
for who and what needs one: the four protagonists, every opponent, staff
member, visitor and reporter, every card, every stage. Each file is listed
with a tick when it has been drawn and a blank box when it has not, grouped
so the most-seen art comes first.

Nothing here decides anything. It only reads the data and looks on disk, so
it is safe to run as often as you like.
"""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATA = REPO / "data"
OUTPUT = REPO / "design" / "ART_CHECKLIST.md"


def load(name):
    return json.loads((DATA / f"{name}.json").read_text(encoding="utf-8"))


def on_disk(res_path: str) -> Path:
    return REPO / res_path.replace("res://", "")


def ids(rows, key):
    if isinstance(rows, dict):
        for value in rows.values():
            if isinstance(value, list):
                rows = value
                break
    return [str(row[key]) for row in rows if isinstance(row, dict) and row.get(key)]


def main():
    art = load("art")
    folders = art["folders"]
    legacy = art.get("legacy_folders", {})
    faces = art["expressions"]
    extras = art.get("optional_expressions", [])

    def drawn(folder_kind, filename, legacy_kind=None):
        if on_disk(folders[folder_kind] + filename).exists():
            return True
        return bool(legacy_kind and legacy.get(legacy_kind)
                    and on_disk(legacy[legacy_kind] + filename).exists())

    player = load("player")
    groups = [
        ("Protagonists", "protagonist",
         [(p["player_id"], p.get("name_en", "")) for p in player["protagonists"]], True),
        ("Opponents", "opponent",
         [(o["opp_id"], o.get("name", "")) for o in load("opponents")], False),
        ("Staff", "staff",
         [(s["staff_id"], s.get("name", "")) for s in load("staff")], False),
        ("Visitors", "visitor",
         [(v["visitor_id"], v.get("name", v.get("name_en", ""))) for v in load("visitors")], False),
        ("Reporters", "journalist",
         [(j["journalist_id"], j.get("name", "")) for j in load("journalists")["journalists"]], False),
    ]

    lines = [
        "# Art checklist",
        "",
        "Generated by `tools/art_checklist.py` from the data files. Do not edit by",
        "hand; re-run it after adding art. Where each file goes, and the sizes, are",
        "in `data/art.json`.",
        "",
    ]
    summary = []
    body = []

    for title, kind, people, wants_extras in groups:
        wanted = faces + (extras if wants_extras else [])
        done = total = 0
        section = [f"## {title} — `{folders[kind].replace('res://', '')}`", "",
                   "| ID | Name | " + " | ".join(wanted) + " |",
                   "|---|---|" + "---|" * len(wanted)]
        for person_id, name in people:
            cells = []
            for face in wanted:
                ok = drawn(kind, f"{person_id}_{face}.png", "character")
                done += ok
                total += 1
                cells.append("✓" if ok else "☐")
            section.append(f"| {person_id} | {name} | " + " | ".join(cells) + " |")
        summary.append(f"| {title} | {done} / {total} |")
        body += section + [""]

    def flat(title, kind, items, legacy_kind=None):
        done = sum(drawn(kind, f"{i}.png", legacy_kind) for i, _ in items)
        summary.append(f"| {title} | {done} / {len(items)} |")
        section = [f"## {title} — `{folders[kind].replace('res://', '')}`", "", "| File | For | Drawn |", "|---|---|---|"]
        for item_id, name in items:
            ok = drawn(kind, f"{item_id}.png", legacy_kind)
            section.append(f"| {item_id}.png | {name} | {'✓' if ok else '☐'} |")
        body.extend(section + [""])

    flat("Card art", "card", [(c["card_id"], c.get("name_en", "")) for c in load("cards")], "card")
    flat("Backgrounds", "background",
         [("OFFICE", "The Office")] + [(s["stage_id"], s.get("name_en", "")) for s in load("stages")])
    flat("Organisation icons", "icon", [(b["booster_id"], b.get("name_en", "")) for b in load("boosters")])

    lines += ["| Kind | Drawn |", "|---|---|"] + summary + [""] + body
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO)}")
    for row in summary:
        print("  " + row.strip("|").replace(" | ", ": "))


if __name__ == "__main__":
    main()
